### ISSUE TITLE
logic error in getAllGroups()

### ISSUE THREAD

**Issue by goobadaddy** [strebl/ldap-auth#11]
I'm not an LDAP guy, so maybe this is only for us, but in LdapAuthUserProvider.php:269 says

```
                    if (substr($splitGroup, 0, 3) !== 'DC=') {
                        $grps[substr($splitGroup, '3')] = substr($splitGroup, '3');
                    }
```

Our groups return without the "DC=", so my groups array in Laravel looks like:

```
"groups": {
    "ain Users": "ain Users",  // should be "Domain Users"
    "rs": "rs"  // should be "Users"
}
```

If the purpose is to replace out the strings that start with DC=, then it seems to me like it should be:

```
                    if (substr($splitGroup, 0, 3) !== 'DC=') {
                        $grps[$splitGroup] = $splitGroup;
                    } else {
                        $grps[substr($splitGroup, '3')] = substr($splitGroup, '3');
                    }
```

Unless, again, this is just a quirk with our IT dept's set up.

Thanks.

**Comment by strebl** [comment]
Hi @goobadaddy 

I found the error. Will fix it now!

**Comment by strebl** [comment]
It happens only if recursive_group is set to true.

**Comment by strebl** [comment]
@goobadaddy try the newest version.
Should now work as expected.
