### ISSUE TITLE
Can't Access AD Properties of Logged In User

### ISSUE THREAD

**Issue by brockwddb** [strebl/ldap-auth#12]
Hello -

I'm running into a few problems that I'm having trouble overcoming, which is accessing the properties that are available to the Active Directory user, such as their full name, groups, etc.

As per the documentation that is provided, adding the fields value to the auth.php configuration file should make them accessible, but it appears it isn't working properly.

``` php
'fields' => ['displayname', 'givenname']
```

I added the above line, but when trying to access the logged in user's display name, it always returns null.

``` php
return dd(\Auth::user()->displayname); // returns null
```

Any help would be greatly appreciated. Thank you for your help!

**Comment by kathmann** [comment]
I have tested this and have the same issue, the LDAP attributes are not added to the User model as is decribed in the docs, whether or not I use the 'fields' array in my config/auth.php.
Running Laravel 5.1, user authentication work fine otherwise.

**Comment by strebl** [comment]
Sorry guys for letting you wait that long. A lot of things on my todo list before vacation.

A common error I see is that the model don't allow to fill the properties.
Laravel protects you against Mass Assignment. Try to add the `['displayname', 'givenname']`to your `$fillable` field of your model.

Does that help?

**Comment by kathmann** [comment]
Hi Manuel,

Thanks for the response. I've changed the `$fillable` in my User model as you indicated:
`protected $fillable = ['username', 'displayName'];`

But alas, the displayName is still not filled.

The `$fields` in my config/auth.php is:
`'fields' => ['displayName']`

I've also tried adding a 'displayName' to my users table, but still no dice.

**Comment by strebl** [comment]
Sorry, my bad. Missed something.

The fields array should be an array of key/value pairs.

``` php
'fields' => [
    'username' => 'samaccountname',
    'name' => 'displayName',
    'first_name' => 'givenName',
    'last_name' => 'sn',
],
```

The key is the attribute name you chose for your application. The value is the attribute name given by the directory.

Let me know if that solved your problem.

**Comment by koeus88** [comment]
I'm experiencing the same issue as well. Here is my auth.php file.

``` php
'fields' => [
    'username' => 'samaccountname',
    'name' => 'displayName',
    'firstname' => 'givenName',
    'lastname' => 'sn',
    'groups' => 'memberOf',
],
```

I was able to get this going with some help over at reddit, but my problem came down to not having the following in my User.php file.

``` php
protected $fillable = [
    'username', 'groups', 'name', 'firstname', 'lastname'
];
```

**Comment by strebl** [comment]
Yes, that is what I said some comments [above](https://github.com/strebl/ldap-auth/issues/12#issuecomment-122212795). I tries to fill the model which can't be done if it is protected against mass assignment.

**Comment by brockwddb** [comment]
It appears to be working fine now. The package works quite well, but I feel as if the documentation is a bit lackluster. 

It isn't easy to get support for issues that are with third party packages. I posted on 3 separate forums with no responses. It might be a good idea to update the documentation so that other newbies aren't struggling with this issue.

**Comment by strebl** [comment]
Yeah I totally see that.
But I need help for the docs. My English knowledge is just to limited.

On the other side, I just forked the package without cleaning the documentation. I'll do that.
