### ISSUE TITLE
ErrorException in LdapAuthUserProvider.php line 249: Undefined offset: 1

### ISSUE THREAD

**Issue by spaldos** [strebl/ldap-auth#15]
New to Github so not really sure where to post this, but I was getting this error when trying to log in with an account that didn't exist.

Changing to the following seemed to fix it.

```
return count($groups) > 1 ? substr($groups[1], '3') : null;
```

**Comment by strebl** [comment]
Welcome @spaldos to GitHub :+1: 

Thanks for reporting this issue.
I'll look into that.

**Comment by brunowego** [comment]
+1

## 

Thanks @spaldos :+1:

**Comment by strebl** [comment]
The issue only appears if `primarygroups` is in the fields list.
