### ISSUE TITLE
getAllGroups() returns Key=Value Array

### ISSUE THREAD

**Issue by ChrOst** [strebl/ldap-auth#21]
Hi strebl,

is there a proper reason why you are doing this?
https://github.com/strebl/ldap-auth/blob/master/src/LdapAuthUserProvider.php#L268
Just returning $groups would make more sense for me.

Best regards,
ChrOst

**Comment by strebl** [comment]
Hi @ChrOst 

Yeah, I can tell you that.
`$groups` has integer keys.
`array_combine($groups, $groups)` transforms the array and sets the key equal to the value.

``` php
// Before array_combine
$groups = [
    0 => 'group_1',
    1 => 'group_2'
]

// After array_combine
$groups = [
     'group_1' => 'group_1',
     'group_2' => 'group_2'
]
```

I hope that's a proper reason :smile:

**Comment by ChrOst** [comment]
But wheres the Problem with Integer-Keys?
I'm just wondering if there is a proper reason for storing that data twice?

**Comment by strebl** [comment]
It's an easy way to filter duplicates. This array contains a lot duplicates if recursive_groups is true. Or at least in my AD environment this is the case.

And I think sometimes it's easier to work with.

Did that answer your question?

**Comment by ChrOst** [comment]
yes
