### ISSUE TITLE
BindingResolutionException in Container.php line 744: Target [Illuminate\Contracts\Auth\Access\Gate] is not instantiable.

### ISSUE THREAD

**Issue by brockwddb** [strebl/ldap-auth#24]
Hello, I'm receiving the following error when trying to configure this package on the newest version of Laravel (5.1.1).

`BindingResolutionException in Container.php line 744: Target [Illuminate\Contracts\Auth\Access\Gate] is not instantiable.`

Any help would be greatly appreciated.

**Comment by brockwddb** [comment]
I found a temporary workaround for this.

I commented out the following lines in `/app/Providers/AuthServiceProvider` and it seems to work fine. I'm assuming this isn't the proper fix for this problem, however.

``` php
    public function boot(GateContract $gate)
    {
        parent::registerPolicies($gate);

        //
    }
```

**Comment by strebl** [comment]
Will look into that on sunday. Thanks @brockwddb for reporting the issue!

**Comment by brockwddb** [comment]
No problem @strebl. Thank you for looking into it.

**Comment by strebl** [comment]
Hey @brockwddb I can't replicate your problem.

I had an v5.1.3 Laravel test app, worked fine.
After updating Laravel to 5.1.17 (currently the newest version), app is still working.
After that, I follwed the optional [upgrade guide](http://laravel.com/docs/5.1/upgrade#upgrade-5.1.11) - App still working.

I think its I typo, but you wrote that you are on v5.1.1, on which version are you?

**Comment by brockwddb** [comment]
5.1.16 (LTS) is the version I'm referring to. Sorry - typo.

Edit: I also upgraded to 5.1.17 and am receiving the same error.

**Comment by strebl** [comment]
Can you post your providers array in your config/app.php file?

**Comment by brockwddb** [comment]
```
'providers' => [

    /*
     * Laravel Framework Service Providers...
     */
    Illuminate\Foundation\Providers\ArtisanServiceProvider::class,
    Ccovey\LdapAuth\LdapAuthServiceProvider::class,
    Illuminate\Broadcasting\BroadcastServiceProvider::class,
    Illuminate\Bus\BusServiceProvider::class,
    Illuminate\Cache\CacheServiceProvider::class,
    Illuminate\Foundation\Providers\ConsoleSupportServiceProvider::class,
    Illuminate\Routing\ControllerServiceProvider::class,
    Illuminate\Cookie\CookieServiceProvider::class,
    Illuminate\Database\DatabaseServiceProvider::class,
    Illuminate\Encryption\EncryptionServiceProvider::class,
    Illuminate\Filesystem\FilesystemServiceProvider::class,
    Illuminate\Foundation\Providers\FoundationServiceProvider::class,
    Illuminate\Hashing\HashServiceProvider::class,
    Illuminate\Mail\MailServiceProvider::class,
    Illuminate\Pagination\PaginationServiceProvider::class,
    Illuminate\Pipeline\PipelineServiceProvider::class,
    Illuminate\Queue\QueueServiceProvider::class,
    Illuminate\Redis\RedisServiceProvider::class,
    Illuminate\Auth\Passwords\PasswordResetServiceProvider::class,
    Illuminate\Session\SessionServiceProvider::class,
    Illuminate\Translation\TranslationServiceProvider::class,
    Illuminate\Validation\ValidationServiceProvider::class,
    Illuminate\View\ViewServiceProvider::class,

    /*
     * Application Service Providers...
     */
    App\Providers\AppServiceProvider::class,
    App\Providers\AuthServiceProvider::class,
    App\Providers\EventServiceProvider::class,
    App\Providers\RouteServiceProvider::class,

 ],
```

I just did a fresh install of Laravel 5.1.17 and tried adding the provider and got the same error.

**Comment by strebl** [comment]
Okay I see the problem now.

Try to add `Illuminate\Auth\AuthServiceProvider::class` again.
Before `Ccovey\LdapAuth\LdapAuthServiceProvider::class`.

If that works, I'll update the docs.

**Comment by brockwddb** [comment]
Yes - appears to be working for me now.

**Comment by strebl** [comment]
Thanks @brockwddb for providing information and helping to resolve this issue!
