### ISSUE TITLE
How do I access userlist?

### ISSUE THREAD

**Issue by shawndibble** [strebl/ldap-auth#27]
Thank you for this service. I have it setup and working fine with ldap, however I cannot figure out how to access the ldap userlist. Could you explain how I can grab it via one of my controllers?

According to the inline comments, it is suppose to have all the data in Auth::user(). However I have dd that out and couldn't see any userList and when I do Auth::user()->userList, I get null.

Honestly I just want the ability to check against the list of users in ldap and ensure my userlist is up-to-date. And if not, add any missing users.

**Comment by strebl** [comment]
Hmm that's a little bit harder to solve.

Do get all Active Directory users, you have to grab them with the underlying adldap class.
There is no built-in sync mechanism.

But before you start, please read following issue https://github.com/strebl/ldap-auth/issues/25 and consider to switch to the new package.
