### ISSUE TITLE
Switching from adldap/adldap to Adldap2/Adldap2

### ISSUE THREAD

**Issue by strebl** [strebl/ldap-auth#8]
I'm going to switch the dependency to the new [Adldap2/Adldap2](https://github.com/Adldap2/Adldap2) repository after it hits stable. It's the modern version of the original adldap/adldap.
It's even possible that the changes getting merged to the original repository.

**Comment by brunowego** [comment]
:+1:

**Comment by strebl** [comment]
Closing this issue. Read #25 for details.
