### ISSUE TITLE
Configuration issue

### ISSUE THREAD

**Issue by collinsjd** [strebl/ldap-auth#9]
I found that this part:

> To set up your adLDAP for connections to your domain controller, create a file app/config/adldap.php
> This will provide all the configuration values for your connection.

was incorrect. I had to add the config options to ConfigServiceProvider.php

**Comment by strebl** [comment]
Hi @collinsjd 
Can you give me an example?
I didn't edit the ConfigServiceProvider and it works.

**Comment by collinsjd** [comment]
My domain/config options -- I had to place the return array into ConfigServiceProvider.php in order for ldap-auth to see them (it never tried to load any settings from app/config/adldap.php)

**Comment by strebl** [comment]
ahh... I see where the problem is.
It should be config/adldap.php and not app/config/adldap.php.
app/config/adldap.php is the old Laravel 4 path.
I'll update the readme file.

**Comment by strebl** [comment]
Fixed with fd25b238795f04a88ac7e3205fae2ebbac9159e6.
